version: 2

sources:
  - name: erpnext_raw
    schema: erpnext_raw
    tables:
      - name: tab_journal_entry
        identifier: tab_journal_entry

      - name: tab_journal_entry_account
        identifier: tab_journal_entry_account

      - name: tab_purchase_invoice
        identifier: tab_purchase_invoice

      - name: tab_purchase_invoice_item
        identifier: tab_purchase_invoice_item

      - name: tab_sales_invoice
        identifier: tab_sales_invoice

      - name: tab_sales_invoice_item
        identifier: tab_sales_invoice_item