version: 2

sources:
  - name: erpnext_raw
    schema: erpnext_raw
    tables:
      - name: tab_journal_entry
        identifier: tab_journal_entry

      - name: tab_journal_entry_account
        identifier: tab_journal_entry_account